//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pixellation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pixellation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeremi Emánuel Kádár.
        /// </summary>
        public static string AboutCreditsAuthor {
            get {
                return ResourceManager.GetString("AboutCreditsAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design, Programming, Icons.
        /// </summary>
        public static string AboutCreditsHeader {
            get {
                return ResourceManager.GetString("AboutCreditsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Pixellation.
        /// </summary>
        public static string AboutDialogTitle {
            get {
                return ResourceManager.GetString("AboutDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIT License, Copyright (c) 2020-2021 Kádár Jeremi Emánuel.
        /// </summary>
        public static string AboutLicenseContent {
            get {
                return ResourceManager.GetString("AboutLicenseContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string AboutLicenseHeader {
            get {
                return ResourceManager.GetString("AboutLicenseHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixellation Pixelart Editor.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string DefaultFrameName {
            get {
                return ResourceManager.GetString("DefaultFrameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string DefaultLayerName {
            get {
                return ResourceManager.GetString("DefaultLayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved Project.
        /// </summary>
        public static string DefaultProjectTitle {
            get {
                return ResourceManager.GetString("DefaultProjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Files (*.png, *.bmp, *.jpg, *.tiff, *.gif)|*.png;*.bmp;*.jpg;*.tiff;*.gif.
        /// </summary>
        public static string ExportFilter {
            get {
                return ResourceManager.GetString("ExportFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to json.
        /// </summary>
        public static string ExtensionForDataFile {
            get {
                return ResourceManager.GetString("ExtensionForDataFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pxel.
        /// </summary>
        public static string ExtensionForProjectFilePackage {
            get {
                return ResourceManager.GetString("ExtensionForProjectFilePackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FramesCaretaker.
        /// </summary>
        public static string FramesCaretakerKey {
            get {
                return ResourceManager.GetString("FramesCaretakerKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image And Pixellation Project Files (*.bmp, *.jpg, *.png, *.tiff, *.pxel)|*.bmp;*.jpg;*.png;*.tiff;*.pxel.
        /// </summary>
        public static string OpenFileFilter {
            get {
                return ResourceManager.GetString("OpenFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to metadata.
        /// </summary>
        public static string PackageContentFileNameForMetaData {
            get {
                return ResourceManager.GetString("PackageContentFileNameForMetaData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to project.
        /// </summary>
        public static string PackageContentFileNameForProjectData {
            get {
                return ResourceManager.GetString("PackageContentFileNameForProjectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToolInstancePrimary.
        /// </summary>
        public static string PrimaryToolInstanceKey {
            get {
                return ResourceManager.GetString("PrimaryToolInstanceKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixellation Project Files (*.pxel)|*.pxel.
        /// </summary>
        public static string SaveFileFilter {
            get {
                return ResourceManager.GetString("SaveFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToolInstanceSecondary.
        /// </summary>
        public static string SecondaryToolInstanceKey {
            get {
                return ResourceManager.GetString("SecondaryToolInstanceKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixellation.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
